package com.lapsa.kz.country;

public enum KZCity {
    ABAI(KZCityType.DIST_CENTER, KZArea.OKGD),
    AKKOL(KZCityType.DIST_CENTER, KZArea.OAKM),
    AKSAI(KZCityType.DIST_CENTER, KZArea.OZK),
    AKSU(KZCityType.REGION_SUB, KZArea.OPVL),
    AKTAU(KZCityType.REGION_CENTER, KZArea.OMNG),
    AKTOBE(KZCityType.REGION_CENTER, KZArea.OAKT),
    ALGA(KZCityType.DIST_CENTER, KZArea.OAKT),
    ALM(KZCityType.MAJOR, KZArea.GALM),
    ARAL(KZCityType.DIST_CENTER, KZArea.OKZL),
    ARKAL(KZCityType.REGION_SUB, KZArea.OKST),
    ARYS(KZCityType.REGION_SUB, KZArea.OUK),
    AST(KZCityType.MAJOR, KZArea.GAST),
    ATB(KZCityType.DIST_CENTER, KZArea.OAKM),
    ATY(KZCityType.REGION_CENTER, KZArea.OATY),
    AYAG(KZCityType.DIST_CENTER, KZArea.OVK),
    BAIKON(KZCityType.MAJOR, KZArea.RUSAGEN),
    BALH(KZCityType.REGION_SUB, KZArea.OKGD),
    BULA(KZCityType.DIST_CENTER, KZArea.OSK),
    DERZH(KZCityType.DIST_CENTER, KZArea.OAKM),
    EREIM(KZCityType.DIST_CENTER, KZArea.OAKM),
    ESIK(KZCityType.DIST_CENTER, KZArea.OALM),
    ESIL(KZCityType.DIST_CENTER, KZArea.OAKM),
    ZHANO(KZCityType.REGION_SUB, KZArea.OMNG),
    ZHANAT(KZCityType.DIST_CENTER, KZArea.OZHM),
    ZHARK(KZCityType.DIST_CENTER, KZArea.OALM),
    ZHZKZ(KZCityType.REGION_SUB, KZArea.OKGD),
    ZHEM(KZCityType.DIST_SUB, KZArea.OAKT),
    ZHETYSAY(KZCityType.DIST_CENTER, KZArea.OUK),
    ZHITIKARA(KZCityType.DIST_CENTER, KZArea.OKST),
    ZAISAN(KZCityType.DIST_CENTER, KZArea.OVK),
    ZYRIAN(KZCityType.REGION_SUB, KZArea.OVK),
    KAZAL(KZCityType.DIST_SUB, KZArea.OKZL),
    KANDYA(KZCityType.DIST_CENTER, KZArea.OAKT),
    KAPCH(KZCityType.DIST_CENTER, KZArea.OALM),
    KGND(KZCityType.REGION_CENTER, KZArea.OKGD),
    KARAZH(KZCityType.REGION_SUB, KZArea.OKGD),
    KARAT(KZCityType.DIST_CENTER, KZArea.OZHM),
    KARKAR(KZCityType.DIST_CENTER, KZArea.OKGD),
    KASKEL(KZCityType.DIST_CENTER, KZArea.OALM),
    KENTAU(KZCityType.DIST_CENTER, KZArea.OUK),
    KOKSH(KZCityType.REGION_CENTER, KZArea.OAKM),
    KOSTN(KZCityType.REGION_CENTER, KZArea.OKST),
    KYLSAR(KZCityType.DIST_CENTER, KZArea.OATY),
    KURCH(KZCityType.REGION_SUB, KZArea.OVK),
    KYZYL(KZCityType.REGION_CENTER, KZArea.OKZL),
    LENGER(KZCityType.DIST_CENTER, KZArea.OUK),
    LISAK(KZCityType.DIST_CENTER, KZArea.OKST),
    MAKIN(KZCityType.DIST_CENTER, KZArea.OAKM),
    MAMLY(KZCityType.DIST_CENTER, KZArea.OSK),
    PAVL(KZCityType.REGION_CENTER, KZArea.OPVL),
    PETRP(KZCityType.REGION_CENTER, KZArea.OSK),
    PRIOZ(KZCityType.REGION_SUB, KZArea.OKGD),
    RIDDR(KZCityType.REGION_SUB, KZArea.OVK),
    RUDNI(KZCityType.REGION_SUB, KZArea.OKST),
    SARAN(KZCityType.REGION_SUB, KZArea.OKGD),
    SARKND(KZCityType.DIST_CENTER, KZArea.OALM),
    SARYAG(KZCityType.DIST_CENTER, KZArea.OUK),
    SATP(KZCityType.REGION_SUB, KZArea.OKGD),
    SEMEI(KZCityType.REGION_SUB, KZArea.OVK),
    SERGEE(KZCityType.DIST_CENTER, KZArea.OSK),
    SEREBR(KZCityType.REGION_SUB, KZArea.OVK),
    STEPNOG(KZCityType.REGION_SUB, KZArea.OAKM),
    STEPNY(KZCityType.DIST_CENTER, KZArea.OAKM),
    TAIYN(KZCityType.DIST_CENTER, KZArea.OSK),
    TALGAR(KZCityType.DIST_CENTER, KZArea.OALM),
    TALDYK(KZCityType.REGION_CENTER, KZArea.OALM),
    TARAZ(KZCityType.REGION_CENTER, KZArea.OZHM),
    TEKEL(KZCityType.REGION_SUB, KZArea.OALM),
    TEMIR(KZCityType.DIST_SUB, KZArea.OAKT),
    TEMRT(KZCityType.REGION_SUB, KZArea.OKGD),
    TURK(KZCityType.REGION_SUB, KZArea.OUK),
    URALS(KZCityType.REGION_CENTER, KZArea.OZK),
    UKAM(KZCityType.REGION_CENTER, KZArea.OVK),
    USHAR(KZCityType.DIST_CENTER, KZArea.OALM),
    USHTB(KZCityType.DIST_CENTER, KZArea.OALM),
    FRSH(KZCityType.REGION_SUB, KZArea.OMNG),
    HROM(KZCityType.DIST_CENTER, KZArea.OAKT),
    SHARD(KZCityType.DIST_CENTER, KZArea.OUK),
    SHALK(KZCityType.DIST_CENTER, KZArea.OAKT),
    SHAR(KZCityType.REGION_SUB, KZArea.OVK),
    SHKH(KZCityType.REGION_SUB, KZArea.OKGD),
    SHMN(KZCityType.DIST_CENTER, KZArea.OVK),
    SHU(KZCityType.DIST_CENTER, KZArea.OZHM),
    SHYM(KZCityType.REGION_CENTER, KZArea.OUK),
    SCHU(KZCityType.DIST_CENTER, KZArea.OAKM),
    EKIB(KZCityType.REGION_SUB, KZArea.OPVL),
    EMBA(KZCityType.DIST_SUB, KZArea.OAKT);

    public static final String BUNDLE_BASENAME = "KZLibLocalization";

    private final KZCityType type;
    private final KZArea area;

    KZCity(KZCityType type, KZArea area) {
	this.type = type;
	this.area = area;
    }

    public KZCityType getType() {
	return type;
    }

    public KZArea getArea() {
	return area;
    }
}
